### ISSUE TITLE
label fusion in mindboggle 101 dataset

### ISSUE THREAD

**Issue by zhangliutong** [lihaoliu-cambridge/unsupervised-medical-image-segmentation#1]
I wonder if you follow the FAIM to use the label_list_25 to calculate the dice, and then fuse that into 5 regions to get the final result.

**Comment by lihaoliu-cambridge** [comment]
Yes, I followed this setting.

**Comment by zhangliutong** [comment]
I am confused that why not first fuse the regions into 5 ROIs, and then calculate the ROI dice.

**Comment by lihaoliu-cambridge** [comment]
Actually, you can. 

Since in the training process you didn’t use any segmentation mask, you can also use the fuse-first segmentation mask for evaluation as long as you compare with other methods on this kind of segmentation mask.

**Comment by zhangliutong** [comment]
Thank you so much. Do you use the mingboggle 101 in MNI152 space and LPB40 in delineation space?
