### ISSUE TITLE
Not probabilistic model

### ISSUE THREAD

**Issue by han-liu** [lihaoliu-cambridge/unsupervised-medical-image-segmentation#2]
Based on your codes, it seems that your voxelmorph model was not a probabilistic model, i.e., your deformation field was directly obtained from the U-net output instead of being sampled from a distribution. Also, your smoothness loss seems different from your description in your paper. Could you please clarify on that please? Thanks.

**Comment by lihaoliu-cambridge** [comment]
> Based on your codes, it seems that your voxelmorph model was not a probabilistic model, i.e., your deformation field was directly obtained from the U-net output instead of being sampled from a distribution. Also, your smoothness loss seems different from your description in your paper. Could you please clarify on that please? Thanks.

Hi, thanks for your question. Yes, the currently provided code is not a probabilistic model. 

Our model is mainly built based on VoxelMorph. For VoxelMorph, there are two classic architectures: CVPR2018 and MICCAI2018. CVPR2018 is not a probabilistic model that obtains the deformation field directly. Whilst MICCAI2018 is a probabilistic model as described in the paper. The currently provided code in this repo is the CVPR2018 architecture (not a probabilistic model).

We will modify the project description to eliminate this confusion and upload the MICCAI2018 architecture as soon as possible.
